//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tester
    {
        public string Name { get; set; }
        public Nullable<int> Pin { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Id { get; set; }
        public bool Active { get; set; }
    }
}
