//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBatt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.58")]
        public double LED_Red_On_Val {
            get {
                return ((double)(this["LED_Red_On_Val"]));
            }
            set {
                this["LED_Red_On_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.042")]
        public double LED_Green_On_Val {
            get {
                return ((double)(this["LED_Green_On_Val"]));
            }
            set {
                this["LED_Green_On_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double LED_Yellow_On_Val {
            get {
                return ((double)(this["LED_Yellow_On_Val"]));
            }
            set {
                this["LED_Yellow_On_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.27")]
        public double LED_Red_Off_Val {
            get {
                return ((double)(this["LED_Red_Off_Val"]));
            }
            set {
                this["LED_Red_Off_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00098")]
        public double LED_Green_Off_Val {
            get {
                return ((double)(this["LED_Green_Off_Val"]));
            }
            set {
                this["LED_Green_Off_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double LED_Yellow_Off_Val {
            get {
                return ((double)(this["LED_Yellow_Off_Val"]));
            }
            set {
                this["LED_Yellow_Off_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogsBatt")]
        public string Log_Folder {
            get {
                return ((string)(this["Log_Folder"]));
            }
            set {
                this["Log_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zeus.zpl")]
        public string ZPL_Lable_File {
            get {
                return ((string)(this["ZPL_Lable_File"]));
            }
            set {
                this["ZPL_Lable_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.29.250.59")]
        public string Printer_Address {
            get {
                return ((string)(this["Printer_Address"]));
            }
            set {
                this["Printer_Address"] = value;
            }
        }
    }
}
