//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDiags
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CentraliteEntities : DbContext
    {
        public CentraliteEntities()
            : base("name=CentraliteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MacAddress> MacAddresses { get; set; }
    
        public virtual int GetNextMac(Nullable<long> startBlock, Nullable<long> endBlock, ObjectParameter newMac)
        {
            var startBlockParameter = startBlock.HasValue ?
                new ObjectParameter("StartBlock", startBlock) :
                new ObjectParameter("StartBlock", typeof(long));
    
            var endBlockParameter = endBlock.HasValue ?
                new ObjectParameter("EndBlock", endBlock) :
                new ObjectParameter("EndBlock", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNextMac", startBlockParameter, endBlockParameter, newMac);
        }
    }
}
