//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDiags
{
    using System;
    using System.Collections.Generic;
    
    public partial class LowesHub
    {
        public int Id { get; set; }
        public int mac_id { get; set; }
        public string smt_serial { get; set; }
        public int hw_ver { get; set; }
        public int customer_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual LowesCustomer LowesCustomer { get; set; }
        public virtual MacAddress MacAddress { get; set; }
    }
}
