//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDiags
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationSiteId
    {
        public int Id { get; set; }
        public string StationMac { get; set; }
    
        public virtual StationSite StationSite { get; set; }
    }
}
