//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZDiags.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COM_DUT {
            get {
                return ((string)(this["COM_DUT"]));
            }
            set {
                this["COM_DUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COM_BLE {
            get {
                return ((string)(this["COM_BLE"]));
            }
            set {
                this["COM_BLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97207484672")]
        public long MAC_Lowes_Block_Start {
            get {
                return ((long)(this["MAC_Lowes_Block_Start"]));
            }
            set {
                this["MAC_Lowes_Block_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97207582463")]
        public long MAC_Lowes_Block_End {
            get {
                return ((long)(this["MAC_Lowes_Block_End"]));
            }
            set {
                this["MAC_Lowes_Block_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogDiags")]
        public string Log_Folder {
            get {
                return ((string)(this["Log_Folder"]));
            }
            set {
                this["Log_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public double LED_Red_On_Val {
            get {
                return ((double)(this["LED_Red_On_Val"]));
            }
            set {
                this["LED_Red_On_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double LED_Red_Off_Val {
            get {
                return ((double)(this["LED_Red_Off_Val"]));
            }
            set {
                this["LED_Red_Off_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.9")]
        public double LED_Yellow_On_Val {
            get {
                return ((double)(this["LED_Yellow_On_Val"]));
            }
            set {
                this["LED_Yellow_On_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double LED_Yellow_Off_Val {
            get {
                return ((double)(this["LED_Yellow_Off_Val"]));
            }
            set {
                this["LED_Yellow_Off_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.79")]
        public double LED_Green_On_Val {
            get {
                return ((double)(this["LED_Green_On_Val"]));
            }
            set {
                this["LED_Green_On_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double LED_Green_Off_Val {
            get {
                return ((double)(this["LED_Green_Off_Val"]));
            }
            set {
                this["LED_Green_Off_Val"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Victor Martin")]
        public string Operator {
            get {
                return ((string)(this["Operator"]));
            }
            set {
                this["Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int HwVer {
            get {
                return ((int)(this["HwVer"]));
            }
            set {
                this["HwVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRIS")]
        public string Costumer {
            get {
                return ((string)(this["Costumer"]));
            }
            set {
                this["Costumer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97207582464")]
        public long MAC_Centralite_Block_Start {
            get {
                return ((long)(this["MAC_Centralite_Block_Start"]));
            }
            set {
                this["MAC_Centralite_Block_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97207647999")]
        public long MAC_Centralite_Block_End {
            get {
                return ((long)(this["MAC_Centralite_Block_End"]));
            }
            set {
                this["MAC_Centralite_Block_End"] = value;
            }
        }
    }
}
